[target.x86_64-unknown-linux-gnu]
image = "cnosdb/cross:x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image = "cnosdb/cross:aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "cnosdb/cross:x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
image = "cnosdb/cross:aarch64-unknown-linux-musl"

[target.armv7-unknown-linux-gnueabihf]
image = "cnosdb/cross:armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-musleabihf]
image = "cnosdb/cross:armv7-unknown-linux-musleabihf"


# https://gist.github.com/Emilgardis/83fae58858edc3d773f278241b0327b7
