name: Jenkins CI

on:
  push:
    branches: [ "jenkins" ]
  pull_request:
    types: [opened, reopened]
    branches: [ "jenkins" ]
jobs:
  prJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - run: |
          env
