name: Jenkins CI

on:
  push:
    branches: [ "jenkins" ]
  pull_request:
    types: [opened, reopened]
    branches: [ "jenkins" ]
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
jobs:
  prJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$GITHUB_PR_NUMBER"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build single job
      uses: Mondtic/build-jenkins-job@master
      with:
        jenkins-url: ${{ secrets.JENKINS_URL }}
        jenkins-token: ${{ secrets.JENKINS_TOKEN }}
        jenkins-user: ${{ secrets.JENKINS_USER }}
        jenkins-job: ${{ secrets.JENKINS_JOB }}
        jenkins-job-params: "{\"stringparam\": \"${{ GITHUB_PR_NUMBER }}\"}"
        jenkins-wait-job: "wait"
        jenkins-ssl-verify: "false"
