name: Rust

on:
  push:
    branches: ["cross-latest"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        wget https://github.com/google/flatbuffers/releases/download/v22.9.29/Linux.flatc.binary.clang++-12.zip
        unzip Linux.flatc.binary.clang++-12.zip
        mv flatc /usr/bin
        apt-get update
        apt-get install -y protobuf-compiler
    - name: Download the compilation tool
      run: cargo install cross
    - name: Cross compile
      run: |
        /usr/bin/protoc
        cross build --workspace --bins
