name: Rust

on:
  push:
    branches: ["cross-latest"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Build Dependencies
      shell: bash
      run: |
        curl -o flatbuffers.zip -sL https://github.com/google/flatbuffers/releases/download/v22.9.29/Linux.flatc.binary.clang++-12.zip
        unzip  flatbuffers.zip
        mv flatc /usr/local/bin
    - name: Install Protoc
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Install cross-rs
      run: cargo install cross
    - name: Cargo compile
      run: ｜
        cargo build --workspace --bins
