ame: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]
    branches: [ "main" ]
jobs:
  prJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - run: |
          env
